### ISSUE TITLE
Docker build failed due to php extension sockets

### ISSUE THREAD

**Issue by ThomasBoom89** [ThomasBoom89/thingiverse-zip-downloader#2]
Currently the latest docker image of php breaks docker build due to the php extension sockets.
https://github.com/docker-library/php/issues/1245

**Comment by delboy1978uk** [comment]
you can use the new versions like this until they fix it:
```
RUN CFLAGS="$CFLAGS -D_GNU_SOURCE" docker-php-ext-install sockets
```

**Comment by ThomasBoom89** [comment]
@delboy1978uk thank you very much for this advice. When I noticed this issue from the build pocess, I checked locally if the last version will break too. Because it didn't, I pushed my changes upstream. I realized there was a working solution for it in the docker-library repository but my changes where already made. Both are temporarily solution until it is fixed in the upstream docker-library.
