### ISSUE TITLE
Blank page download.php

### ISSUE THREAD

**Issue by wizz666** [ThomasBoom89/thingiverse-zip-downloader#6]
When trying to download i get a blank page and no download. 
It seems that thingiverse has changed there code to hide the download url the application is currently scraping.

Any solution for this?

**Comment by ThomasBoom89** [comment]
Thank you for pointing out! Currently the application is not working!

The download elements have no longer href attributes in the dom. The files are now hidden behind the thingiverse api. I will change the strategy to scrape the javascript bundles to access the api.

**Comment by ThomasBoom89** [comment]
This [Commit](https://github.com/ThomasBoom89/thingiverse-zip-downloader/commit/67c6f7ad6561b673ea6488718210db6c2697a510) should fix the current problems. 
I also added an update section to the readme.

**Comment by wizz666** [comment]
> This [Commit](https://github.com/ThomasBoom89/thingiverse-zip-downloader/commit/67c6f7ad6561b673ea6488718210db6c2697a510) should fix the current problems. I also added an update section to the readme.

Thanks will try that today and see how it works.

**Comment by wizz666** [comment]
Fast question. 
Can i just replace the old files with the new or do i need to do a new installation?

**Comment by ThomasBoom89** [comment]
If you did clone the repo with git and havend changed anything you can do a 'git pull'. It will replace all necessary files. If you did it manuel via zip or something you have to replace them on your own. So yes, replace is the easiest way to go. See Update section in the Readme, there is a guide for both options (if using git).

**Comment by wizz666** [comment]
Thanks got it to work and it works fine :) 
Just had to change the port again in the docker-compose.yml 
And now all works fine :)

**Comment by ThomasBoom89** [comment]
Great :+1: 
I will improve the documention for the port change so it will be clear in future.
